### ISSUE TITLE
Gyro Hiact

### ISSUE THREAD

**Issue by Pascal66** [kd8bxp/livera_robot#1]
Not really an issue.
I was you are active on bot
I'm back to my hicat (not maintened with no news from makers, little shame for 99€ no ?)

So, i wish to use the acceleretometer and gyro embedded in the hicat board.

Do you have any clues ?

Thank you

**Comment by kd8bxp** [comment]
hicat.io is full of documentation for the board. I've not used the accelerometer, but the site says it is a mpu6050 connected to I2C D2:SDA, D3:SCL, and interrupt pin D7 - I would suspect you need a MPU6050 library. 
http://hicat.io/Livera-Documentation/#livera
hope that helps, I've not worked with this board since the kickstarter.

**Comment by Pascal66** [comment]
Thank you. I found what I need.
I'm looking to change the card with a sony spresence, when my projects are done

**Comment by kd8bxp** [comment]
Your welcome, have a good night.
